### ISSUE TITLE
CLI test failure

### ISSUE THREAD

**Issue by pitrou** [dask/dask-drmaa#26]
I'm trying to run the tests locally (mimicking steps in the Travis-Ci configuration file), but I get this error:
```
$ docker exec -it sge_master /bin/bash -c "cd /dask-drmaa; py.test dask_drmaa/cli -vs --tb=native"
========================================================== test session starts ==========================================================
platform linux -- Python 3.6.0, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /opt/anaconda/bin/python
cachedir: .cache
rootdir: /dask-drmaa, inifile:
collected 1 items 

dask_drmaa/cli/tests/test_dask_drmaa.py::test_dask_drmaa distributed.utils - ERROR - Timed out trying to connect to 'tcp://127.0.0.1:8786' after 5 s: ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/comm/core.py", line 169, in connect
    quiet_exceptions=EnvironmentError)
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.gen.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/utils.py", line 212, in f
    result[0] = yield make_coro()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/client.py", line 518, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/client.py", line 550, in _ensure_connected
    connection_args=self.connection_args)
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/comm/core.py", line 178, in connect
    _raise(error)
  File "/opt/anaconda/lib/python3.6/site-packages/distributed/comm/core.py", line 161, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://127.0.0.1:8786' after 5 s: ConnectionRefusedError: [Errno 111] Connection refused


Print from stderr
=================
b'distributed.scheduler - INFO -   Scheduler at:    tcp://172.18.0.2:32890\n'b'distributed.scheduler - INFO -       bokeh at:              0.0.0.0:8787\n'b'distributed.scheduler - INFO - Scheduler closing...\n'b'distributed.scheduler - INFO - Scheduler closing all comms\n'

Print from stdout
=================
FAILED

```

Judging by the stderr, it seems expected that connecting to `tcp://127.0.0.1:8786` fails if the scheduler is actually listening on `tcp://172.18.0.2:32890` (i.e. on a different IP *and* port)...

**Comment by mrocklin** [comment]
The scheduler is created on the local machine (with LocalCluster) so the IP
difference shouldn't matter.  I can't explain the port difference.

**Comment by pitrou** [comment]
Now it also fails on Travis-CI:
https://travis-ci.org/dask/dask-drmaa/builds/235681387#L1830

I think the reason is that I changed LocalCluster to listen on a random port by default, rather than port 8786. I was assuming that LocalClusters are always used with `Client(cluster)`, not for connecting independently...

**Comment by pitrou** [comment]
I included a fix in https://github.com/dask/dask-drmaa/pull/29.
